/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import controlador.MetodosContrasena;
import controlador.MetodosCuenta;
import java.awt.Color;
import controlador.MetodosRegistroCuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier Sanchez Gonzalez
 */
public class Cuenta extends javax.swing.JPanel {

    /**
     * Inicilizacion variables
     */
    private String email;
    private String matricula;
    private boolean esCoche;
    private String nuevaContrasena;
    private boolean contrasenaValida;
    private String hashContrasena;


    // Metodos utilizados
    MetodosRegistroCuenta mrc = new MetodosRegistroCuenta();
    MetodosCuenta cuenta = new MetodosCuenta();
    MetodosContrasena mc = new MetodosContrasena();

    /**
     * Creates new form RegistroCuenta
     */
    public Cuenta() {
        initComponents();

       

        // Poner jTexfield y jBotton el radio
        jtmatricula.putClientProperty("FlatLaf.style", "arc: 15");
        jtcontrasena.putClientProperty("FlatLaf.style", "arc: 15");
        jtemail.putClientProperty("FlatLaf.style", "arc: 15");
        jbmodificar.putClientProperty("FlatLaf.style", "arc: 15");
        jbborrar.putClientProperty("FlatLaf.style", "arc: 15");
        jbcancelar.putClientProperty("FlatLaf.style", "arc: 15");
        jbcontrasena.putClientProperty("FlatLaf.style", "arc: 15");

        //jlcuentausuario.putClientProperty("FlatLaf.styleClass", "h1");
        jltitulo2.putClientProperty("FlatLaf.styleClass", "h2");
        jltcontrasena.putClientProperty("FlatLaf.styleClass", "h0");
        jltitulo5.putClientProperty("FlatLaf.styleClass", "h0");

        jlmatricula.putClientProperty("FlatLaf.styleClass", "h3");

        // añadir a los jTextField iconos
        jtemail.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("img/email.svg"));
        jtmatricula.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("img/matricula.svg"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panelCuenta = new vista.PanelRound();
        jlcuentausuario = new javax.swing.JLabel();
        jltitulo2 = new javax.swing.JLabel();
        jbmodificar = new javax.swing.JButton();
        jPanelMatricula = new javax.swing.JPanel();
        jlmatricula = new javax.swing.JLabel();
        jtmatricula = new javax.swing.JTextField();
        jltcontrasena = new javax.swing.JLabel();
        jCheckBoxCoche = new javax.swing.JCheckBox();
        jCheckBoxMoto = new javax.swing.JCheckBox();
        jLiconMoto = new javax.swing.JLabel();
        jLiconCoche = new javax.swing.JLabel();
        jbborrar = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();
        jPanelEmail = new javax.swing.JPanel();
        jlemail = new javax.swing.JLabel();
        jtemail = new javax.swing.JTextField();
        jltitulo5 = new javax.swing.JLabel();
        jCheckBoxEliminarCuenta = new javax.swing.JCheckBox();
        jCheckBoxContraseña = new javax.swing.JCheckBox();
        jbcontrasena = new javax.swing.JButton();
        jltitulo6 = new javax.swing.JLabel();
        jPanelContrasena = new javax.swing.JPanel();
        jlcontrasena = new javax.swing.JLabel();
        jtcontrasena = new javax.swing.JPasswordField();
        jCheckBoxModificar = new javax.swing.JCheckBox();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(428, 800));

        panelCuenta.setBackground(new java.awt.Color(249, 251, 255));
        panelCuenta.setMaximumSize(null);
        panelCuenta.setPreferredSize(new java.awt.Dimension(428, 800));
        panelCuenta.setRoundBottomLeft(30);
        panelCuenta.setRoundBottomRight(30);

        jlcuentausuario.setFont(new java.awt.Font("Stencil", 0, 20)); // NOI18N
        jlcuentausuario.setForeground(new java.awt.Color(39, 59, 244));
        jlcuentausuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlcuentausuario.setText("CUENTA DE USUARIO");
        jlcuentausuario.setPreferredSize(new java.awt.Dimension(273, 30));

        jltitulo2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jltitulo2.setForeground(new java.awt.Color(51, 51, 51));
        jltitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltitulo2.setText("Que desea hacer?");
        jltitulo2.setPreferredSize(new java.awt.Dimension(273, 30));

        jbmodificar.setBackground(new java.awt.Color(43, 220, 61));
        jbmodificar.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jbmodificar.setForeground(new java.awt.Color(255, 255, 255));
        jbmodificar.setText("Modificar");
        jbmodificar.setToolTipText("Boton para modificar los datos");
        jbmodificar.setPreferredSize(new java.awt.Dimension(124, 49));
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });

        jPanelMatricula.setBackground(new java.awt.Color(249, 251, 255));
        jPanelMatricula.setPreferredSize(new java.awt.Dimension(335, 82));

        jlmatricula.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlmatricula.setForeground(new java.awt.Color(25, 35, 66));
        jlmatricula.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlmatricula.setText("Matricula");
        jlmatricula.setPreferredSize(new java.awt.Dimension(51, 17));

        jtmatricula.setBackground(new java.awt.Color(198, 212, 255));
        jtmatricula.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jtmatricula.setForeground(new java.awt.Color(153, 153, 153));
        jtmatricula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtmatricula.setText("Matricula");
        jtmatricula.setToolTipText("Introduce una matricula valida 4 numeros separado por un guion y dos letras en mayusculas");
        jtmatricula.setPreferredSize(new java.awt.Dimension(335, 50));
        jtmatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtmatriculaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMatriculaLayout = new javax.swing.GroupLayout(jPanelMatricula);
        jPanelMatricula.setLayout(jPanelMatriculaLayout);
        jPanelMatriculaLayout.setHorizontalGroup(
            jPanelMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMatriculaLayout.createSequentialGroup()
                .addGroup(jPanelMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelMatriculaLayout.setVerticalGroup(
            jPanelMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMatriculaLayout.createSequentialGroup()
                .addComponent(jlmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jltcontrasena.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jltcontrasena.setForeground(new java.awt.Color(25, 35, 66));
        jltcontrasena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltcontrasena.setText("Nueva contraseña");
        jltcontrasena.setPreferredSize(new java.awt.Dimension(273, 30));

        jCheckBoxCoche.setBackground(new java.awt.Color(249, 251, 255));
        buttonGroup.add(jCheckBoxCoche);
        jCheckBoxCoche.setForeground(new java.awt.Color(39, 59, 244));
        jCheckBoxCoche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxCoche.setMaximumSize(null);
        jCheckBoxCoche.setMinimumSize(null);
        jCheckBoxCoche.setPreferredSize(new java.awt.Dimension(25, 19));

        jCheckBoxMoto.setBackground(new java.awt.Color(249, 251, 255));
        buttonGroup.add(jCheckBoxMoto);
        jCheckBoxMoto.setForeground(new java.awt.Color(39, 59, 244));
        jCheckBoxMoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxMoto.setMaximumSize(null);
        jCheckBoxMoto.setMinimumSize(null);
        jCheckBoxMoto.setPreferredSize(new java.awt.Dimension(25, 19));

        jLiconMoto.setBackground(new java.awt.Color(39, 59, 244));
        jLiconMoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/motorbike-fill 1.png"))); // NOI18N
        jLiconMoto.setMaximumSize(null);
        jLiconMoto.setMinimumSize(null);
        jLiconMoto.setPreferredSize(new java.awt.Dimension(25, 19));

        jLiconCoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/car-fill 2.png"))); // NOI18N
        jLiconCoche.setMaximumSize(null);
        jLiconCoche.setMinimumSize(null);
        jLiconCoche.setPreferredSize(new java.awt.Dimension(25, 19));

        jbborrar.setBackground(new java.awt.Color(255, 0, 153));
        jbborrar.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jbborrar.setForeground(new java.awt.Color(255, 255, 255));
        jbborrar.setText("Borrar cuenta");
        jbborrar.setToolTipText("Botón borra la cuenta del usuario");
        jbborrar.setPreferredSize(new java.awt.Dimension(124, 49));
        jbborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbborrarActionPerformed(evt);
            }
        });

        jbcancelar.setBackground(new java.awt.Color(255, 3, 3));
        jbcancelar.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jbcancelar.setForeground(new java.awt.Color(255, 255, 255));
        jbcancelar.setText("Cancelar");
        jbcancelar.setToolTipText("Boton cancela operacion y regresa a la pantalla anterior");
        jbcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcancelar.setPreferredSize(new java.awt.Dimension(124, 49));
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });

        jPanelEmail.setBackground(new java.awt.Color(249, 251, 255));
        jPanelEmail.setPreferredSize(new java.awt.Dimension(335, 82));

        jlemail.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlemail.setForeground(new java.awt.Color(25, 35, 66));
        jlemail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlemail.setText("Email");
        jlemail.setPreferredSize(new java.awt.Dimension(51, 17));

        jtemail.setBackground(new java.awt.Color(198, 212, 255));
        jtemail.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jtemail.setForeground(new java.awt.Color(153, 153, 153));
        jtemail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtemail.setText("Email");
        jtemail.setToolTipText("Introduce un email valido, Minimo: 1 letra mayuscula, 1 letra minuscula, 1 caracter especial, 1 numero.");
        jtemail.setPreferredSize(new java.awt.Dimension(335, 50));
        jtemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtemailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelEmailLayout = new javax.swing.GroupLayout(jPanelEmail);
        jPanelEmail.setLayout(jPanelEmailLayout);
        jPanelEmailLayout.setHorizontalGroup(
            jPanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmailLayout.createSequentialGroup()
                .addComponent(jlemail, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jtemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEmailLayout.setVerticalGroup(
            jPanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmailLayout.createSequentialGroup()
                .addComponent(jlemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jltitulo5.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jltitulo5.setForeground(new java.awt.Color(25, 35, 66));
        jltitulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltitulo5.setText("Introduce tu email");
        jltitulo5.setPreferredSize(new java.awt.Dimension(273, 30));

        buttonGroup1.add(jCheckBoxEliminarCuenta);
        jCheckBoxEliminarCuenta.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBoxEliminarCuenta.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxEliminarCuenta.setText("Eliminar Cuenta?");
        jCheckBoxEliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEliminarCuentaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jCheckBoxContraseña);
        jCheckBoxContraseña.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBoxContraseña.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxContraseña.setText("Cambiar contraseña?");
        jCheckBoxContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxContraseñaActionPerformed(evt);
            }
        });

        jbcontrasena.setBackground(new java.awt.Color(43, 220, 61));
        jbcontrasena.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jbcontrasena.setForeground(new java.awt.Color(255, 255, 255));
        jbcontrasena.setText("Cambiar contraseña");
        jbcontrasena.setToolTipText("Boton para modificar los datos");
        jbcontrasena.setPreferredSize(new java.awt.Dimension(124, 49));
        jbcontrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcontrasenaActionPerformed(evt);
            }
        });

        jltitulo6.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jltitulo6.setForeground(new java.awt.Color(25, 35, 66));
        jltitulo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltitulo6.setText("Introduce los datos nuevos");
        jltitulo6.setPreferredSize(new java.awt.Dimension(273, 30));

        jPanelContrasena.setBackground(new java.awt.Color(249, 251, 255));
        jPanelContrasena.setPreferredSize(new java.awt.Dimension(335, 82));

        jlcontrasena.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlcontrasena.setForeground(new java.awt.Color(25, 35, 66));
        jlcontrasena.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlcontrasena.setText("Contraseña");
        jlcontrasena.setPreferredSize(new java.awt.Dimension(51, 17));

        jtcontrasena.setBackground(new java.awt.Color(198, 212, 255));
        jtcontrasena.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jtcontrasena.setForeground(new java.awt.Color(153, 153, 153));
        jtcontrasena.setText("********");
        jtcontrasena.setToolTipText("Introduce una contraseña entre 8 y 10 caracteres");
        jtcontrasena.setPreferredSize(new java.awt.Dimension(335, 50));
        jtcontrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtcontrasenaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelContrasenaLayout = new javax.swing.GroupLayout(jPanelContrasena);
        jPanelContrasena.setLayout(jPanelContrasenaLayout);
        jPanelContrasenaLayout.setHorizontalGroup(
            jPanelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContrasenaLayout.createSequentialGroup()
                .addComponent(jlcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jtcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanelContrasenaLayout.setVerticalGroup(
            jPanelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContrasenaLayout.createSequentialGroup()
                .addComponent(jlcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jtcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        buttonGroup1.add(jCheckBoxModificar);
        jCheckBoxModificar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckBoxModificar.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxModificar.setText("Modificar?");
        jCheckBoxModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCuentaLayout = new javax.swing.GroupLayout(panelCuenta);
        panelCuenta.setLayout(panelCuentaLayout);
        panelCuentaLayout.setHorizontalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuentaLayout.createSequentialGroup()
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuentaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCuentaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jlcuentausuario, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCuentaLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jbborrar, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                        .addComponent(jbmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbcontrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanelContrasena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                        .addGroup(panelCuentaLayout.createSequentialGroup()
                                            .addComponent(jPanelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLiconCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jCheckBoxCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(27, 27, 27)
                                            .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jCheckBoxMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLiconMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jltitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jltitulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCuentaLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jCheckBoxEliminarCuenta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxContraseña)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jltcontrasena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelCuentaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCuentaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jltitulo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelCuentaLayout.setVerticalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuentaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlcuentausuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jltitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxContraseña)
                    .addComponent(jCheckBoxEliminarCuenta)
                    .addComponent(jCheckBoxModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jltitulo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jltcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCuentaLayout.createSequentialGroup()
                        .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLiconCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLiconMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jbcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbborrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuentaLayout.createSequentialGroup()
                    .addContainerGap(388, Short.MAX_VALUE)
                    .addComponent(jltitulo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(382, 382, 382)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Metodo verifica que los campos no esten vacios, llama al metodo
     * modifcarVehiculo.
     *
     * @param evt
     */
    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed

        email = jtemail.getText();
        matricula = jtmatricula.getText();
        esCoche = jCheckBoxCoche.isSelected();

        if (email.isEmpty() || email.equals("Email") || matricula.equals("Matricula") || matricula.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos antes de continuar", "Campos Incompletos", JOptionPane.ERROR_MESSAGE);
        } else {
            if (MetodosRegistroCuenta.modificarDatosVehiculo(email, matricula, esCoche)) {
                jtmatricula.setText("Matricula");
                jtmatricula.setForeground(Color.gray);
                jtemail.setText("Email");
                jtemail.setForeground(Color.gray);
                jCheckBoxCoche.setSelected(false);
                jCheckBoxMoto.setSelected(false);
                JOptionPane.showMessageDialog(null, "Vehículo modificado", "Modificado", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "El vehículo no ha sido modificado", "Modificado", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbmodificarActionPerformed

    /**
     * Metodo comprueba que el campo no este vacio, le pasamos el email al
     * metodo elimnarUsuario si eiste lo eliminara de la base de datos.
     *
     * @param evt
     */
    private void jbborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbborrarActionPerformed

        email = jtemail.getText();

        if (jtemail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos antes de continuar", "Campos Incompletos", JOptionPane.ERROR_MESSAGE);
        } else {
            if (MetodosRegistroCuenta.eliminarUsuario(email)) {
                JOptionPane.showMessageDialog(null, "Usuario eliminado", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Usuario no ha sido eliminado", "Eliminado", JOptionPane.ERROR_MESSAGE);
            }
        }

        jtmatricula.setText("Matricula");
        jtmatricula.setForeground(Color.gray);
        jtemail.setText("Email");
        jtemail.setForeground(Color.gray);


    }//GEN-LAST:event_jbborrarActionPerformed
    /**
     * Metodo le pasa la accion de campo cuando se introducen los datos se
     * comporte de una cierta manera del comportamientoCampos.
     *
     * @param evt
     */
    private void jtmatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtmatriculaMouseClicked
        mrc.comportamientoCampos(jtmatricula, "Matricula");
    }//GEN-LAST:event_jtmatriculaMouseClicked

    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed

        // Crea una instancia de InicioCuenta
        InicioCuenta ic = new InicioCuenta();
        // Muestra la ventana InicioCuenta
        mostrarPanel(ic);

    }//GEN-LAST:event_jbcancelarActionPerformed
    /**
     * Metodo le pasa la accion de campo cuando se introducen los datos se
     * comporte de una cierta manera del comportamientoCampos.
     *
     * @param evt
     */
    private void jtemailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtemailMouseClicked
        mrc.comportamientoCampos(jtemail, "Email");
    }//GEN-LAST:event_jtemailMouseClicked
    /**
     * Metodo en el que al seleccionar el checbox activa o desactiva las
     * acciones necesarias para ese mentodo
     *
     * @param evt
     */
    private void jCheckBoxEliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEliminarCuentaActionPerformed
        boolean seleciondoEliminar = jCheckBoxEliminarCuenta.isSelected();

        if (seleciondoEliminar) {
            jtmatricula.setEnabled(false);
            jCheckBoxMoto.setEnabled(false);
            jCheckBoxCoche.setEnabled(false);
            jbmodificar.setEnabled(false);
            jbcontrasena.setEnabled(false);
            jtcontrasena.setEnabled(false);

            // Desactivar los otros checkbox
            jCheckBoxContraseña.setEnabled(false);
            jCheckBoxModificar.setEnabled(false);
        } else {
            jtmatricula.setEnabled(true);
            jCheckBoxMoto.setEnabled(true);
            jCheckBoxCoche.setEnabled(true);
            jbmodificar.setEnabled(true);
            // Habilitar solo el checkbox correspondiente a la acción seleccionada
            jCheckBoxContraseña.setEnabled(true);
            jCheckBoxModificar.setEnabled(true);
        }


    }//GEN-LAST:event_jCheckBoxEliminarCuentaActionPerformed
    /**
     * Metodo en el que al seleccionar el checbox activa o desactiva las
     * acciones necesarias para ese mentodo
     *
     * @param evt
     */
    private void jCheckBoxContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxContraseñaActionPerformed
        boolean seleciondoContrasena = jCheckBoxContraseña.isSelected();

        if (seleciondoContrasena) {
            jtmatricula.setEnabled(false);
            jCheckBoxMoto.setEnabled(false);
            jCheckBoxCoche.setEnabled(false);
            jbmodificar.setEnabled(false);
            jbborrar.setEnabled(false);

            // Desactivar los otros checkbox
            jCheckBoxEliminarCuenta.setEnabled(false);
            jCheckBoxModificar.setEnabled(false);
        } else {
            jtmatricula.setEnabled(true);
            jCheckBoxMoto.setEnabled(true);
            jCheckBoxCoche.setEnabled(true);
            jbmodificar.setEnabled(true);
            // Habilitar solo el checkbox correspondiente a la acción seleccionada
            jCheckBoxEliminarCuenta.setEnabled(true);
            jCheckBoxModificar.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBoxContraseñaActionPerformed
    /**
     * Metodo se le pasa la contraseña la al metodo ValdiarContraseña, nos
     * devuelve y se la pasamos al metodo crearHasContraseña, genera un hash y
     * lo pasarmos al metodo modificarContraseña para actualizarla.
     *
     * @param evt
     */
    private void jbcontrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcontrasenaActionPerformed

        nuevaContrasena = String.valueOf(jtcontrasena.getPassword());

        contrasenaValida = mc.validarContrasena(nuevaContrasena);

        if (contrasenaValida) {
            hashContrasena = mc.crearHashContrasena(nuevaContrasena, nuevaContrasena);
            System.out.print(hashContrasena);
            if (cuenta.modificarContraseña(email, hashContrasena)) {
                JOptionPane.showMessageDialog(null, "Contraseña modificada correctamente.", "Modificación de contraseña", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "La contraseña no cumple con los requisitos mínimos.", "Contraseña no valida", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jbcontrasenaActionPerformed

    private void jtcontrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtcontrasenaMouseClicked
        mrc.comportamientoCampos(jtcontrasena, "********");
    }//GEN-LAST:event_jtcontrasenaMouseClicked
    /**
     * Metodo en el que al seleccionar el checbox activa o desactiva las
     * acciones necesarias para ese mentodo
     *
     * @param evt
     */
    private void jCheckBoxModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxModificarActionPerformed
        boolean seleciondoModicar = jCheckBoxModificar.isSelected();

        if (seleciondoModicar) {
            jbcontrasena.setEnabled(false);
            jtcontrasena.setEnabled(false);
            jbborrar.setEnabled(false);

            // Desactivar los otros checkbox
            jCheckBoxEliminarCuenta.setEnabled(false);
            jCheckBoxContraseña.setEnabled(false);
        } else {
            jbborrar.setEnabled(true);
            jbcontrasena.setEnabled(true);
            jtcontrasena.setEnabled(true);

            // Habilitar solo el checkbox correspondiente a la acción seleccionada
            jCheckBoxEliminarCuenta.setEnabled(true);
            jCheckBoxContraseña.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBoxModificarActionPerformed
    /**
     * Metodo al que se le pase el panel de IncioCuenta, elimnanco el anterior y
     * mostrando el nuevo panel
     *
     * @param panel
     */
    private void mostrarPanel(InicioCuenta panel) {
        panel.setSize(428, 800);
        panel.setLocation(0, 0);

        panelCuenta.removeAll();
        panelCuenta.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        panelCuenta.revalidate();
        panelCuenta.repaint();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox jCheckBoxCoche;
    private javax.swing.JCheckBox jCheckBoxContraseña;
    private javax.swing.JCheckBox jCheckBoxEliminarCuenta;
    private javax.swing.JCheckBox jCheckBoxModificar;
    private javax.swing.JCheckBox jCheckBoxMoto;
    private javax.swing.JLabel jLiconCoche;
    private javax.swing.JLabel jLiconMoto;
    private javax.swing.JPanel jPanelContrasena;
    private javax.swing.JPanel jPanelEmail;
    private javax.swing.JPanel jPanelMatricula;
    private javax.swing.JButton jbborrar;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbcontrasena;
    private javax.swing.JButton jbmodificar;
    private javax.swing.JLabel jlcontrasena;
    private javax.swing.JLabel jlcuentausuario;
    private javax.swing.JLabel jlemail;
    private javax.swing.JLabel jlmatricula;
    private javax.swing.JLabel jltcontrasena;
    private javax.swing.JLabel jltitulo2;
    private javax.swing.JLabel jltitulo5;
    private javax.swing.JLabel jltitulo6;
    private javax.swing.JPasswordField jtcontrasena;
    private javax.swing.JTextField jtemail;
    private javax.swing.JTextField jtmatricula;
    private vista.PanelRound panelCuenta;
    // End of variables declaration//GEN-END:variables

}
