/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import controlador.MetodosRegistroCuenta;


/**
 *
 * @author Javier Sanchez Gonzalez
 */
public class Cuenta extends javax.swing.JPanel {

 
    
    // Variables
    /**
     * 
     */
    private boolean esCoche;
    private String nombre;
    private String apellidos;
    private String matricula;
    private String email;
    private String contrasena;
    private  String repetirContrasena;
   
    MetodosRegistroCuenta mrc = new MetodosRegistroCuenta();
 
    /**
     * Creates new form RegistroCuenta
     */
    public Cuenta() {
        initComponents();
        
        // Poner jTexfield y jBotton el radio
        jtnombre.putClientProperty("FlatLaf.style","arc: 15");
        jtapellidos.putClientProperty("FlatLaf.style","arc: 15");
        jtmatricula.putClientProperty("FlatLaf.style","arc: 15");

        
        jbmodificar.putClientProperty("FlatLaf.style","arc: 15");
        jbborrar.putClientProperty("FlatLaf.style","arc: 15");
 
        //jlcuentausuario.putClientProperty("FlatLaf.styleClass", "h1");
        jltitulo2.putClientProperty("FlatLaf.styleClass", "h2");
          jltitulo4.putClientProperty("FlatLaf.styleClass", "h0");
        jlvolver.putClientProperty("FlatLaf.styleClass", "h3");
        jlnombre.putClientProperty("FlatLaf.styleClass", "h3");
        jlapellidos.putClientProperty("FlatLaf.styleClass", "h3");
        jlmatricula.putClientProperty("FlatLaf.styleClass", "h3");

      
        // añadir a los jTextField iconos
        jtnombre.putClientProperty( FlatClientProperties.TEXT_FIELD_LEADING_ICON,new FlatSVGIcon( "img/usuario.svg" ) );
        jtapellidos.putClientProperty( FlatClientProperties.TEXT_FIELD_LEADING_ICON,new FlatSVGIcon( "img/email.svg" ) );
        jtmatricula.putClientProperty( FlatClientProperties.TEXT_FIELD_LEADING_ICON,new FlatSVGIcon( "img/matricula.svg" ) );
      /*  String matricula = jtmatricula.setText();
        matricula.LineReader.CAPITALIZE_WORD*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCuenta = new vista.PanelRound();
        jlcuentausuario = new javax.swing.JLabel();
        jltitulo2 = new javax.swing.JLabel();
        jbmodificar = new javax.swing.JButton();
        jPanelNombre = new javax.swing.JPanel();
        jlnombre = new javax.swing.JLabel();
        jtnombre = new javax.swing.JTextField();
        jPanelEmail = new javax.swing.JPanel();
        jlapellidos = new javax.swing.JLabel();
        jtapellidos = new javax.swing.JTextField();
        jPanelMatricula = new javax.swing.JPanel();
        jlmatricula = new javax.swing.JLabel();
        jtmatricula = new javax.swing.JTextField();
        jltitulo4 = new javax.swing.JLabel();
        jCheckBoxCoche = new javax.swing.JCheckBox();
        jCheckBoxMoto = new javax.swing.JCheckBox();
        jlvolver = new javax.swing.JLabel();
        jLiconMoto = new javax.swing.JLabel();
        jLiconCoche = new javax.swing.JLabel();
        jbborrar = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(428, 800));

        panelCuenta.setBackground(new java.awt.Color(249, 251, 255));
        panelCuenta.setMaximumSize(null);
        panelCuenta.setPreferredSize(new java.awt.Dimension(428, 800));
        panelCuenta.setRoundBottomLeft(30);
        panelCuenta.setRoundBottomRight(30);

        jlcuentausuario.setFont(new java.awt.Font("Stencil", 0, 20)); // NOI18N
        jlcuentausuario.setForeground(new java.awt.Color(39, 59, 244));
        jlcuentausuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlcuentausuario.setText("Cuenta usuario");
        jlcuentausuario.setPreferredSize(new java.awt.Dimension(273, 30));

        jltitulo2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jltitulo2.setForeground(new java.awt.Color(51, 51, 51));
        jltitulo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jltitulo2.setText("Que desea hacer?");
        jltitulo2.setPreferredSize(new java.awt.Dimension(273, 30));

        jbmodificar.setBackground(new java.awt.Color(39, 59, 244));
        jbmodificar.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jbmodificar.setForeground(new java.awt.Color(255, 255, 255));
        jbmodificar.setText("Modificar datos usuario");
        jbmodificar.setToolTipText("Boton para modificar los datos");
        jbmodificar.setPreferredSize(new java.awt.Dimension(124, 49));
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });

        jPanelNombre.setBackground(new java.awt.Color(249, 251, 255));
        jPanelNombre.setPreferredSize(new java.awt.Dimension(335, 82));

        jlnombre.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlnombre.setForeground(new java.awt.Color(25, 35, 66));
        jlnombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlnombre.setText("Nombre");
        jlnombre.setPreferredSize(new java.awt.Dimension(51, 17));

        jtnombre.setBackground(new java.awt.Color(198, 212, 255));
        jtnombre.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jtnombre.setForeground(new java.awt.Color(153, 153, 153));
        jtnombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtnombre.setText("Nombre");
        jtnombre.setToolTipText("Introduce tu nombre minimo tiene que tener 3 caracteres");
        jtnombre.setPreferredSize(new java.awt.Dimension(335, 50));
        jtnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtnombreMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelNombreLayout = new javax.swing.GroupLayout(jPanelNombre);
        jPanelNombre.setLayout(jPanelNombreLayout);
        jPanelNombreLayout.setHorizontalGroup(
            jPanelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNombreLayout.createSequentialGroup()
                .addComponent(jlnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelNombreLayout.setVerticalGroup(
            jPanelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNombreLayout.createSequentialGroup()
                .addComponent(jlnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelEmail.setBackground(new java.awt.Color(249, 251, 255));
        jPanelEmail.setPreferredSize(new java.awt.Dimension(335, 82));

        jlapellidos.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlapellidos.setForeground(new java.awt.Color(25, 35, 66));
        jlapellidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlapellidos.setText("Apellidos");
        jlapellidos.setPreferredSize(new java.awt.Dimension(51, 17));

        jtapellidos.setBackground(new java.awt.Color(198, 212, 255));
        jtapellidos.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jtapellidos.setForeground(new java.awt.Color(153, 153, 153));
        jtapellidos.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtapellidos.setText("Apellidos");
        jtapellidos.setToolTipText("Introduce un email valido");
        jtapellidos.setPreferredSize(new java.awt.Dimension(335, 50));
        jtapellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtapellidosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelEmailLayout = new javax.swing.GroupLayout(jPanelEmail);
        jPanelEmail.setLayout(jPanelEmailLayout);
        jPanelEmailLayout.setHorizontalGroup(
            jPanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmailLayout.createSequentialGroup()
                .addComponent(jlapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jtapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEmailLayout.setVerticalGroup(
            jPanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmailLayout.createSequentialGroup()
                .addComponent(jlapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelMatricula.setBackground(new java.awt.Color(249, 251, 255));
        jPanelMatricula.setPreferredSize(new java.awt.Dimension(335, 82));

        jlmatricula.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlmatricula.setForeground(new java.awt.Color(25, 35, 66));
        jlmatricula.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlmatricula.setText("Matricula");
        jlmatricula.setPreferredSize(new java.awt.Dimension(51, 17));

        jtmatricula.setBackground(new java.awt.Color(198, 212, 255));
        jtmatricula.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jtmatricula.setForeground(new java.awt.Color(153, 153, 153));
        jtmatricula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtmatricula.setText("Matricula");
        jtmatricula.setToolTipText("Introduce una matricula valida 4 numeros separado por un guion y dos letras en mayusculas");
        jtmatricula.setPreferredSize(new java.awt.Dimension(335, 50));
        jtmatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtmatriculaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMatriculaLayout = new javax.swing.GroupLayout(jPanelMatricula);
        jPanelMatricula.setLayout(jPanelMatriculaLayout);
        jPanelMatriculaLayout.setHorizontalGroup(
            jPanelMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMatriculaLayout.createSequentialGroup()
                .addGroup(jPanelMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelMatriculaLayout.setVerticalGroup(
            jPanelMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMatriculaLayout.createSequentialGroup()
                .addComponent(jlmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jltitulo4.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jltitulo4.setForeground(new java.awt.Color(25, 35, 66));
        jltitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltitulo4.setText("Introduce los datos nuevos");
        jltitulo4.setPreferredSize(new java.awt.Dimension(273, 30));

        jCheckBoxCoche.setBackground(new java.awt.Color(249, 251, 255));
        jCheckBoxCoche.setForeground(new java.awt.Color(39, 59, 244));
        jCheckBoxCoche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxCoche.setMaximumSize(null);
        jCheckBoxCoche.setMinimumSize(null);
        jCheckBoxCoche.setPreferredSize(new java.awt.Dimension(25, 19));

        jCheckBoxMoto.setBackground(new java.awt.Color(249, 251, 255));
        jCheckBoxMoto.setForeground(new java.awt.Color(39, 59, 244));
        jCheckBoxMoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxMoto.setMaximumSize(null);
        jCheckBoxMoto.setMinimumSize(null);
        jCheckBoxMoto.setPreferredSize(new java.awt.Dimension(25, 19));

        jlvolver.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jlvolver.setForeground(new java.awt.Color(39, 59, 244));
        jlvolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlvolver.setText("volver");
        jlvolver.setToolTipText("Vuelve a la pantalla anterior");
        jlvolver.setPreferredSize(new java.awt.Dimension(273, 30));
        jlvolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlvolverMouseClicked(evt);
            }
        });

        jLiconMoto.setBackground(new java.awt.Color(39, 59, 244));
        jLiconMoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/motorbike-fill 1.png"))); // NOI18N
        jLiconMoto.setMaximumSize(null);
        jLiconMoto.setMinimumSize(null);
        jLiconMoto.setPreferredSize(new java.awt.Dimension(25, 19));

        jLiconCoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/car-fill 2.png"))); // NOI18N
        jLiconCoche.setMaximumSize(null);
        jLiconCoche.setMinimumSize(null);
        jLiconCoche.setPreferredSize(new java.awt.Dimension(25, 19));

        jbborrar.setBackground(new java.awt.Color(255, 3, 3));
        jbborrar.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jbborrar.setForeground(new java.awt.Color(255, 255, 255));
        jbborrar.setText("Borrar cuenta");
        jbborrar.setToolTipText("Botón borra la cuenta del usuario");
        jbborrar.setPreferredSize(new java.awt.Dimension(124, 49));
        jbborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbborrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCuentaLayout = new javax.swing.GroupLayout(panelCuenta);
        panelCuenta.setLayout(panelCuentaLayout);
        panelCuentaLayout.setHorizontalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuentaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbborrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCuentaLayout.createSequentialGroup()
                        .addComponent(jPanelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLiconCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLiconMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCuentaLayout.createSequentialGroup()
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuentaLayout.createSequentialGroup()
                        .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCuentaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jlcuentausuario, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCuentaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jltitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jltitulo4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCuentaLayout.setVerticalGroup(
            panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuentaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlcuentausuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jltitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jltitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCuentaLayout.createSequentialGroup()
                        .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLiconCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLiconMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addComponent(jbmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbborrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    /** Evento nos lleva a la pantalla de incio de la cuenta*/
    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed
       

    

    }//GEN-LAST:event_jbmodificarActionPerformed
    /** Evento me lleva a la ventana de inicio de sesion*/
    private void jlvolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlvolverMouseClicked
         // Crea una instancia de InicioCuenta
        InicioCuenta ic = new InicioCuenta();
        // Muestra la ventana InicioCuenta
        mostrarPanel(ic);
    }//GEN-LAST:event_jlvolverMouseClicked
    /** Evento si al introducir los datos son erroneos, al cancelar vuelven a incilizarse los campos*/
    private void jbborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbborrarActionPerformed
       
        jtnombre.setText("Nombre");
        jtnombre.setForeground(Color.gray);
        jtapellidos.setText("Email");
        jtapellidos.setForeground(Color.gray);
        jtmatricula.setText("Matricula");
        jtmatricula.setForeground(Color.gray);
  
        
    }//GEN-LAST:event_jbborrarActionPerformed
    /** Evento compotamiento de los campos al seleccionar*/
    private void jtnombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtnombreMouseClicked
    
        mrc.comportamientoCampos(jtnombre, "Nombre");
       
    }//GEN-LAST:event_jtnombreMouseClicked

    private void jtmatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtmatriculaMouseClicked
         mrc.comportamientoCampos(jtmatricula, "Matricula");
    }//GEN-LAST:event_jtmatriculaMouseClicked

    private void jtapellidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtapellidosMouseClicked
        mrc.comportamientoCampos(jtapellidos, "Email");
    }//GEN-LAST:event_jtapellidosMouseClicked
     private void mostrarPanel(InicioCuenta panel) {
       panel.setSize(428, 800);
       panel.setLocation(0,0);  
       
       panelCuenta.removeAll();
       panelCuenta.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
       panelCuenta.revalidate();
       panelCuenta.repaint();
    
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxCoche;
    private javax.swing.JCheckBox jCheckBoxMoto;
    private javax.swing.JLabel jLiconCoche;
    private javax.swing.JLabel jLiconMoto;
    private javax.swing.JPanel jPanelEmail;
    private javax.swing.JPanel jPanelMatricula;
    private javax.swing.JPanel jPanelNombre;
    private javax.swing.JButton jbborrar;
    private javax.swing.JButton jbmodificar;
    private javax.swing.JLabel jlapellidos;
    private javax.swing.JLabel jlcuentausuario;
    private javax.swing.JLabel jlmatricula;
    private javax.swing.JLabel jlnombre;
    private javax.swing.JLabel jltitulo2;
    private javax.swing.JLabel jltitulo4;
    private javax.swing.JLabel jlvolver;
    private javax.swing.JTextField jtapellidos;
    private javax.swing.JTextField jtmatricula;
    private javax.swing.JTextField jtnombre;
    private vista.PanelRound panelCuenta;
    // End of variables declaration//GEN-END:variables

   
  

}
