/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;



/**
 *
 * @author Alumno
 */
public class PantallAlta extends javax.swing.JFrame {

    /**
     * Creates new form PantallAlta
     */
    public PantallAlta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRoundFondo = new vista.PanelRound();
        jLlogoParking = new javax.swing.JLabel();
        jLTitulo1 = new javax.swing.JLabel();
        jLTitulo3 = new javax.swing.JLabel();
        jPanelNombre = new javax.swing.JPanel();
        jLtituloNombre = new javax.swing.JLabel();
        jTnombre = new javax.swing.JTextField();
        jPanelNombre1 = new javax.swing.JPanel();
        jLtituloContrasena = new javax.swing.JLabel();
        jTcontrasena = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLtituloContrasena1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRoundFondo.setBackground(new java.awt.Color(249, 251, 255));
        panelRoundFondo.setMaximumSize(null);
        panelRoundFondo.setPreferredSize(new java.awt.Dimension(428, 800));
        panelRoundFondo.setRoundBottomLeft(30);
        panelRoundFondo.setRoundBottomRight(30);
        panelRoundFondo.setRoundTopLeft(30);
        panelRoundFondo.setRoundTopRight(30);

        jLlogoParking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/LogoParking.png"))); // NOI18N
        jLlogoParking.setText("jLabel1");

        jLTitulo1.setFont(new java.awt.Font("Stencil", 0, 23)); // NOI18N
        jLTitulo1.setForeground(new java.awt.Color(39, 59, 244));
        jLTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo1.setText("¿BUSCAS PLAZAS DE APARCAMIENTO?");
        jLTitulo1.setPreferredSize(new java.awt.Dimension(273, 30));

        jLTitulo3.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLTitulo3.setForeground(new java.awt.Color(25, 35, 66));
        jLTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo3.setText("Inicie sesión o regístrese");
        jLTitulo3.setPreferredSize(new java.awt.Dimension(273, 30));

        jPanelNombre.setBackground(new java.awt.Color(249, 251, 255));
        jPanelNombre.setPreferredSize(new java.awt.Dimension(335, 82));

        jLtituloNombre.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLtituloNombre.setForeground(new java.awt.Color(25, 35, 66));
        jLtituloNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtituloNombre.setText("Nombre");
        jLtituloNombre.setPreferredSize(new java.awt.Dimension(51, 17));

        jTnombre.setBackground(new java.awt.Color(198, 212, 255));
        jTnombre.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jTnombre.setForeground(new java.awt.Color(103, 113, 145));
        jTnombre.setText("Introduce tu nombre");
        jTnombre.setPreferredSize(new java.awt.Dimension(335, 50));

        javax.swing.GroupLayout jPanelNombreLayout = new javax.swing.GroupLayout(jPanelNombre);
        jPanelNombre.setLayout(jPanelNombreLayout);
        jPanelNombreLayout.setHorizontalGroup(
            jPanelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNombreLayout.createSequentialGroup()
                .addGroup(jPanelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLtituloNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelNombreLayout.setVerticalGroup(
            jPanelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNombreLayout.createSequentialGroup()
                .addComponent(jLtituloNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelNombre1.setBackground(new java.awt.Color(249, 251, 255));
        jPanelNombre1.setPreferredSize(new java.awt.Dimension(335, 82));

        jLtituloContrasena.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLtituloContrasena.setForeground(new java.awt.Color(25, 35, 66));
        jLtituloContrasena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtituloContrasena.setText("Contraseña");
        jLtituloContrasena.setPreferredSize(new java.awt.Dimension(51, 17));

        jTcontrasena.setBackground(new java.awt.Color(249, 251, 255));
        jTcontrasena.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jTcontrasena.setForeground(new java.awt.Color(103, 113, 145));
        jTcontrasena.setText("********");
        jTcontrasena.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 59, 244), 1, true));
        jTcontrasena.setPreferredSize(new java.awt.Dimension(335, 50));
        jTcontrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcontrasenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNombre1Layout = new javax.swing.GroupLayout(jPanelNombre1);
        jPanelNombre1.setLayout(jPanelNombre1Layout);
        jPanelNombre1Layout.setHorizontalGroup(
            jPanelNombre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNombre1Layout.createSequentialGroup()
                .addGroup(jPanelNombre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLtituloContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelNombre1Layout.setVerticalGroup(
            jPanelNombre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNombre1Layout.createSequentialGroup()
                .addComponent(jLtituloContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jTcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setBackground(new java.awt.Color(39, 59, 244));
        jButton1.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Recuperar contraseña");
        jButton1.setPreferredSize(new java.awt.Dimension(124, 49));

        jButton2.setBackground(new java.awt.Color(39, 59, 244));
        jButton2.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Iniciar sesión");
        jButton2.setPreferredSize(new java.awt.Dimension(124, 49));

        jButton3.setBackground(new java.awt.Color(39, 59, 244));
        jButton3.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Iniciar sesión");
        jButton3.setPreferredSize(new java.awt.Dimension(124, 49));

        jLtituloContrasena1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLtituloContrasena1.setForeground(new java.awt.Color(0, 0, 0));
        jLtituloContrasena1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtituloContrasena1.setText("O");
        jLtituloContrasena1.setPreferredSize(new java.awt.Dimension(24, 27));

        javax.swing.GroupLayout panelRoundFondoLayout = new javax.swing.GroupLayout(panelRoundFondo);
        panelRoundFondo.setLayout(panelRoundFondoLayout);
        panelRoundFondoLayout.setHorizontalGroup(
            panelRoundFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRoundFondoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelRoundFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLlogoParking, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRoundFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRoundFondoLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jPanelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRoundFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTitulo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRoundFondoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(panelRoundFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanelNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelRoundFondoLayout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLtituloContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelRoundFondoLayout.setVerticalGroup(
            panelRoundFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRoundFondoLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLlogoParking, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRoundFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLtituloContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRoundFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRoundFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTcontrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcontrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcontrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallAlta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLTitulo1;
    private javax.swing.JLabel jLTitulo3;
    private javax.swing.JLabel jLlogoParking;
    private javax.swing.JLabel jLtituloContrasena;
    private javax.swing.JLabel jLtituloContrasena1;
    private javax.swing.JLabel jLtituloNombre;
    private javax.swing.JPanel jPanelNombre;
    private javax.swing.JPanel jPanelNombre1;
    private javax.swing.JTextField jTcontrasena;
    private javax.swing.JTextField jTnombre;
    private vista.PanelRound panelRoundFondo;
    // End of variables declaration//GEN-END:variables
}
