/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import javax.swing.JOptionPane;
import controlador.MetodosRecuperarContraseña;
import controlador.MetodosRegistroCuenta;
import javax.swing.ImageIcon;
/**
 *
 * @author Javier
 */
public class RegistroCuenta extends javax.swing.JPanel {
    // Variables
    private boolean esCoche;
    private String nombre;
    private String apellidos;
    private String matricula;
    private String email;
    private String contrasena;
   
    MetodosRegistroCuenta mrc = new MetodosRegistroCuenta();
 
    /**
     * Creates new form RegistroCuenta
     */
    public RegistroCuenta() {
        initComponents();
        
        // Poner jTexfield y jBotton el radio
        jtnombre.putClientProperty("FlatLaf.style","arc: 15");
        jtapellidos.putClientProperty("FlatLaf.style","arc: 15");
        jtemail.putClientProperty("FlatLaf.style","arc: 15");
        jtmatricula.putClientProperty("FlatLaf.style","arc: 15");
        jtcontrasena.putClientProperty("FlatLaf.style","arc: 15");
        jtrepetirContrasena.putClientProperty("FlatLaf.style","arc: 15");
        
        jbregistro.putClientProperty("FlatLaf.style","arc: 15");
        jbcancelarRegistro.putClientProperty("FlatLaf.style","arc: 15");
 
        jltitulo1.putClientProperty("FlatLaf.styleClass", "h1");
        jltitulo2.putClientProperty("FlatLaf.styleClass", "h3");
        jltitulo3.putClientProperty("FlatLaf.styleClass", "h3");
        jlnombre.putClientProperty("FlatLaf.styleClass", "h3");
        jlapellidos.putClientProperty("FlatLaf.styleClass", "h3");
        jlemail.putClientProperty("FlatLaf.styleClass", "h3");
        jlmatricula.putClientProperty("FlatLaf.styleClass", "h3");
        jlcontrasena.putClientProperty("FlatLaf.styleClass", "h3");
        jlrepetirContrasena.putClientProperty("FlatLaf.styleClass", "h3");
        
      
        // añadir a los jTextField iconos
        jtnombre.putClientProperty( FlatClientProperties.TEXT_FIELD_LEADING_ICON,new FlatSVGIcon( "img/usuario.svg" ) );
        jtapellidos.putClientProperty( FlatClientProperties.TEXT_FIELD_LEADING_ICON,new FlatSVGIcon( "img/apellidos.svg" ) );
        jtemail.putClientProperty( FlatClientProperties.TEXT_FIELD_LEADING_ICON,new FlatSVGIcon( "img/email.svg" ) );
        
        jtmatricula.putClientProperty( FlatClientProperties.TEXT_FIELD_LEADING_ICON,new FlatSVGIcon( "img/matricula.svg" ) );
        jtcontrasena.putClientProperty( FlatClientProperties.TEXT_FIELD_LEADING_ICON,new FlatSVGIcon( "img/candadoCerrado.svg" ) );
        jtrepetirContrasena.putClientProperty( FlatClientProperties.TEXT_FIELD_LEADING_ICON,new FlatSVGIcon( "img/candadoCerrado.svg" ) );
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistroCuenta = new vista.PanelRound();
        jltitulo1 = new javax.swing.JLabel();
        jltitulo2 = new javax.swing.JLabel();
        jbregistro = new javax.swing.JButton();
        jPanelNombre = new javax.swing.JPanel();
        jlnombre = new javax.swing.JLabel();
        jtnombre = new javax.swing.JTextField();
        jPanelApellidos = new javax.swing.JPanel();
        jlapellidos = new javax.swing.JLabel();
        jtapellidos = new javax.swing.JTextField();
        jPanelEmail = new javax.swing.JPanel();
        jlemail = new javax.swing.JLabel();
        jtemail = new javax.swing.JTextField();
        jPanelMatricula = new javax.swing.JPanel();
        jlmatricula = new javax.swing.JLabel();
        jtmatricula = new javax.swing.JTextField();
        jltitulo4 = new javax.swing.JLabel();
        jCheckBoxCoche = new javax.swing.JCheckBox();
        jCheckBoxMoto = new javax.swing.JCheckBox();
        jltitulo3 = new javax.swing.JLabel();
        jPanelContrasena = new javax.swing.JPanel();
        jlcontrasena = new javax.swing.JLabel();
        jtcontrasena = new javax.swing.JPasswordField();
        jPanelContrasena1 = new javax.swing.JPanel();
        jlrepetirContrasena = new javax.swing.JLabel();
        jtrepetirContrasena = new javax.swing.JPasswordField();
        jLiconMoto = new javax.swing.JLabel();
        jLiconCoche = new javax.swing.JLabel();
        jbcancelarRegistro = new javax.swing.JButton();

        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(428, 800));

        panelRegistroCuenta.setBackground(new java.awt.Color(249, 251, 255));
        panelRegistroCuenta.setMaximumSize(null);
        panelRegistroCuenta.setPreferredSize(new java.awt.Dimension(428, 800));
        panelRegistroCuenta.setRoundBottomLeft(30);
        panelRegistroCuenta.setRoundBottomRight(30);

        jltitulo1.setFont(new java.awt.Font("Stencil", 0, 20)); // NOI18N
        jltitulo1.setForeground(new java.awt.Color(39, 59, 244));
        jltitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltitulo1.setText("Registra tu cuenta");
        jltitulo1.setPreferredSize(new java.awt.Dimension(273, 30));

        jltitulo2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jltitulo2.setForeground(new java.awt.Color(51, 51, 51));
        jltitulo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jltitulo2.setText("ya registraste tu cuenta?");
        jltitulo2.setPreferredSize(new java.awt.Dimension(273, 30));

        jbregistro.setBackground(new java.awt.Color(39, 59, 244));
        jbregistro.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jbregistro.setForeground(new java.awt.Color(255, 255, 255));
        jbregistro.setText("Registrarse");
        jbregistro.setToolTipText("Botón para recuparar contraseña ");
        jbregistro.setPreferredSize(new java.awt.Dimension(124, 49));
        jbregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbregistroActionPerformed(evt);
            }
        });

        jPanelNombre.setBackground(new java.awt.Color(249, 251, 255));
        jPanelNombre.setPreferredSize(new java.awt.Dimension(335, 82));

        jlnombre.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlnombre.setForeground(new java.awt.Color(25, 35, 66));
        jlnombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlnombre.setText("Nombre");
        jlnombre.setPreferredSize(new java.awt.Dimension(51, 17));

        jtnombre.setBackground(new java.awt.Color(198, 212, 255));
        jtnombre.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jtnombre.setForeground(new java.awt.Color(153, 153, 153));
        jtnombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtnombre.setText("Nombre");
        jtnombre.setToolTipText("Introduce tu nombre minimo tiene que tener 3 caracteres");
        jtnombre.setPreferredSize(new java.awt.Dimension(335, 50));
        jtnombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtnombreMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelNombreLayout = new javax.swing.GroupLayout(jPanelNombre);
        jPanelNombre.setLayout(jPanelNombreLayout);
        jPanelNombreLayout.setHorizontalGroup(
            jPanelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNombreLayout.createSequentialGroup()
                .addComponent(jlnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelNombreLayout.setVerticalGroup(
            jPanelNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNombreLayout.createSequentialGroup()
                .addComponent(jlnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelApellidos.setBackground(new java.awt.Color(249, 251, 255));
        jPanelApellidos.setPreferredSize(new java.awt.Dimension(335, 82));

        jlapellidos.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlapellidos.setForeground(new java.awt.Color(25, 35, 66));
        jlapellidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlapellidos.setText("Apellidos");
        jlapellidos.setPreferredSize(new java.awt.Dimension(51, 17));

        jtapellidos.setBackground(new java.awt.Color(198, 212, 255));
        jtapellidos.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jtapellidos.setForeground(new java.awt.Color(153, 153, 153));
        jtapellidos.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtapellidos.setText("Apellidos");
        jtapellidos.setToolTipText("Introduce tus apellidos");
        jtapellidos.setPreferredSize(new java.awt.Dimension(335, 50));
        jtapellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtapellidosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelApellidosLayout = new javax.swing.GroupLayout(jPanelApellidos);
        jPanelApellidos.setLayout(jPanelApellidosLayout);
        jPanelApellidosLayout.setHorizontalGroup(
            jPanelApellidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelApellidosLayout.createSequentialGroup()
                .addComponent(jlapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jtapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelApellidosLayout.setVerticalGroup(
            jPanelApellidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelApellidosLayout.createSequentialGroup()
                .addComponent(jlapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelEmail.setBackground(new java.awt.Color(249, 251, 255));
        jPanelEmail.setPreferredSize(new java.awt.Dimension(335, 82));

        jlemail.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlemail.setForeground(new java.awt.Color(25, 35, 66));
        jlemail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlemail.setText("Email");
        jlemail.setPreferredSize(new java.awt.Dimension(51, 17));

        jtemail.setBackground(new java.awt.Color(198, 212, 255));
        jtemail.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jtemail.setForeground(new java.awt.Color(153, 153, 153));
        jtemail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtemail.setText("Email");
        jtemail.setToolTipText("Introduce un email valido");
        jtemail.setPreferredSize(new java.awt.Dimension(335, 50));
        jtemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtemailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelEmailLayout = new javax.swing.GroupLayout(jPanelEmail);
        jPanelEmail.setLayout(jPanelEmailLayout);
        jPanelEmailLayout.setHorizontalGroup(
            jPanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmailLayout.createSequentialGroup()
                .addComponent(jlemail, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jtemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEmailLayout.setVerticalGroup(
            jPanelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmailLayout.createSequentialGroup()
                .addComponent(jlemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelMatricula.setBackground(new java.awt.Color(249, 251, 255));
        jPanelMatricula.setPreferredSize(new java.awt.Dimension(335, 82));

        jlmatricula.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlmatricula.setForeground(new java.awt.Color(25, 35, 66));
        jlmatricula.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlmatricula.setText("Matricula");
        jlmatricula.setPreferredSize(new java.awt.Dimension(51, 17));

        jtmatricula.setBackground(new java.awt.Color(198, 212, 255));
        jtmatricula.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jtmatricula.setForeground(new java.awt.Color(153, 153, 153));
        jtmatricula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtmatricula.setText("Matricula");
        jtmatricula.setToolTipText("Introduce una matricula valida 4 numeros separado por un guion y dos letras en mayusculas");
        jtmatricula.setPreferredSize(new java.awt.Dimension(335, 50));
        jtmatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtmatriculaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMatriculaLayout = new javax.swing.GroupLayout(jPanelMatricula);
        jPanelMatricula.setLayout(jPanelMatriculaLayout);
        jPanelMatriculaLayout.setHorizontalGroup(
            jPanelMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMatriculaLayout.createSequentialGroup()
                .addGroup(jPanelMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelMatriculaLayout.setVerticalGroup(
            jPanelMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMatriculaLayout.createSequentialGroup()
                .addComponent(jlmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jltitulo4.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jltitulo4.setForeground(new java.awt.Color(25, 35, 66));
        jltitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltitulo4.setText("Inicie sesión o regístrese");
        jltitulo4.setPreferredSize(new java.awt.Dimension(273, 30));

        jCheckBoxCoche.setBackground(new java.awt.Color(249, 251, 255));
        jCheckBoxCoche.setForeground(new java.awt.Color(39, 59, 244));
        jCheckBoxCoche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxCoche.setMaximumSize(null);
        jCheckBoxCoche.setMinimumSize(null);
        jCheckBoxCoche.setPreferredSize(new java.awt.Dimension(25, 19));

        jCheckBoxMoto.setBackground(new java.awt.Color(249, 251, 255));
        jCheckBoxMoto.setForeground(new java.awt.Color(39, 59, 244));
        jCheckBoxMoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxMoto.setMaximumSize(null);
        jCheckBoxMoto.setMinimumSize(null);
        jCheckBoxMoto.setPreferredSize(new java.awt.Dimension(25, 19));

        jltitulo3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jltitulo3.setForeground(new java.awt.Color(39, 59, 244));
        jltitulo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jltitulo3.setText("Inicia sesion.");
        jltitulo3.setPreferredSize(new java.awt.Dimension(273, 30));
        jltitulo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jltitulo3MouseClicked(evt);
            }
        });

        jPanelContrasena.setBackground(new java.awt.Color(249, 251, 255));
        jPanelContrasena.setPreferredSize(new java.awt.Dimension(335, 82));

        jlcontrasena.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlcontrasena.setForeground(new java.awt.Color(25, 35, 66));
        jlcontrasena.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlcontrasena.setText("Contraseña");
        jlcontrasena.setPreferredSize(new java.awt.Dimension(51, 17));

        jtcontrasena.setBackground(new java.awt.Color(198, 212, 255));
        jtcontrasena.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jtcontrasena.setForeground(new java.awt.Color(153, 153, 153));
        jtcontrasena.setText("********");
        jtcontrasena.setToolTipText("Introduce una contraseña entre 8 y 10 caracteres");
        jtcontrasena.setPreferredSize(new java.awt.Dimension(335, 50));
        jtcontrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtcontrasenaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelContrasenaLayout = new javax.swing.GroupLayout(jPanelContrasena);
        jPanelContrasena.setLayout(jPanelContrasenaLayout);
        jPanelContrasenaLayout.setHorizontalGroup(
            jPanelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContrasenaLayout.createSequentialGroup()
                .addGroup(jPanelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelContrasenaLayout.setVerticalGroup(
            jPanelContrasenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContrasenaLayout.createSequentialGroup()
                .addComponent(jlcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jtcontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelContrasena1.setBackground(new java.awt.Color(249, 251, 255));
        jPanelContrasena1.setPreferredSize(new java.awt.Dimension(335, 82));

        jlrepetirContrasena.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlrepetirContrasena.setForeground(new java.awt.Color(25, 35, 66));
        jlrepetirContrasena.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlrepetirContrasena.setText("Repetir contraseña");
        jlrepetirContrasena.setPreferredSize(new java.awt.Dimension(51, 17));

        jtrepetirContrasena.setBackground(new java.awt.Color(198, 212, 255));
        jtrepetirContrasena.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jtrepetirContrasena.setForeground(new java.awt.Color(153, 153, 153));
        jtrepetirContrasena.setText("********");
        jtrepetirContrasena.setToolTipText("Introduce una contraseña entre 8 y 10 caracteres");
        jtrepetirContrasena.setPreferredSize(new java.awt.Dimension(335, 50));
        jtrepetirContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtrepetirContrasenaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelContrasena1Layout = new javax.swing.GroupLayout(jPanelContrasena1);
        jPanelContrasena1.setLayout(jPanelContrasena1Layout);
        jPanelContrasena1Layout.setHorizontalGroup(
            jPanelContrasena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContrasena1Layout.createSequentialGroup()
                .addGroup(jPanelContrasena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtrepetirContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlrepetirContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelContrasena1Layout.setVerticalGroup(
            jPanelContrasena1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContrasena1Layout.createSequentialGroup()
                .addComponent(jlrepetirContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jtrepetirContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLiconMoto.setBackground(new java.awt.Color(39, 59, 244));
        jLiconMoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/motorbike-fill 1.png"))); // NOI18N
        jLiconMoto.setMaximumSize(null);
        jLiconMoto.setMinimumSize(null);
        jLiconMoto.setPreferredSize(new java.awt.Dimension(25, 19));

        jLiconCoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/car-fill 2.png"))); // NOI18N
        jLiconCoche.setMaximumSize(null);
        jLiconCoche.setMinimumSize(null);
        jLiconCoche.setPreferredSize(new java.awt.Dimension(25, 19));

        jbcancelarRegistro.setBackground(new java.awt.Color(255, 3, 3));
        jbcancelarRegistro.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jbcancelarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jbcancelarRegistro.setText("Cancelar");
        jbcancelarRegistro.setToolTipText("Botón para recuparar contraseña ");
        jbcancelarRegistro.setPreferredSize(new java.awt.Dimension(124, 49));
        jbcancelarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistroCuentaLayout = new javax.swing.GroupLayout(panelRegistroCuenta);
        panelRegistroCuenta.setLayout(panelRegistroCuentaLayout);
        panelRegistroCuentaLayout.setHorizontalGroup(
            panelRegistroCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroCuentaLayout.createSequentialGroup()
                .addGroup(panelRegistroCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistroCuentaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jltitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistroCuentaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jltitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistroCuentaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jltitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jltitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRegistroCuentaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelRegistroCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistroCuentaLayout.createSequentialGroup()
                        .addComponent(jPanelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelRegistroCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLiconCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(panelRegistroCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLiconMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelRegistroCuentaLayout.createSequentialGroup()
                        .addGroup(panelRegistroCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRegistroCuentaLayout.createSequentialGroup()
                                .addComponent(jbregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbcancelarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelRegistroCuentaLayout.setVerticalGroup(
            panelRegistroCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroCuentaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jltitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jltitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jltitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jltitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(panelRegistroCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistroCuentaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelRegistroCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLiconCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLiconMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRegistroCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxMoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(panelRegistroCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbcancelarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegistroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegistroCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    /** Evento nos lleva a la pantalla de incio de la cuenta*/
    private void jbregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbregistroActionPerformed
        nombre = jtnombre.getText();
        apellidos = jtapellidos.getText();
        
     if (jCheckBoxCoche.isSelected()) {
            esCoche = true;
        } else if (jCheckBoxMoto.isSelected()){
             esCoche = false;
     } else {
            JOptionPane.showMessageDialog(null, "No ha seleccionado tipo de vehículo", "Vehiculo incorrecto", JOptionPane.ERROR_MESSAGE);
        }

    if (jtnombre.getText().isEmpty() || 
    jtapellidos.getText().isEmpty() || 
    jtemail.getText().isEmpty() || 
    jtmatricula.getText().isEmpty() || 
    jtcontrasena.getText().isEmpty() || 
    jtrepetirContrasena.getText().isEmpty() )
     {
    
    // Comprobacion de los campos
    JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos antes de continuar", "Campos Incompletos", JOptionPane.ERROR_MESSAGE);
} else {
    if (jtnombre.getText().length() < 3) {
        JOptionPane.showMessageDialog(null, "El nombre debe contener al menos tres caracteres", "Nombre incorrecto", JOptionPane.ERROR_MESSAGE);
    } else {
         email = jtemail.getText();
        if (!MetodosRecuperarContraseña.esCorreoElectronicoValido(email)) {
            JOptionPane.showMessageDialog(null, "El correo electrónico no es válido", "Correo Electrónico Incorrecto", JOptionPane.ERROR_MESSAGE);
        } else {
             matricula = jtmatricula.getText();
            if (!MetodosRegistroCuenta.validarMatricula(matricula)) {
                JOptionPane.showMessageDialog(null, "La matrícula no es válida", "Matrícula Incorrecta", JOptionPane.ERROR_MESSAGE);
            } else {
                contrasena = jtcontrasena.getText();
                String repetirContrasena = jtrepetirContrasena.getText();
                if (!contrasena.equals(repetirContrasena)) {
                    JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "Contraseñas Incorrectas", JOptionPane.ERROR_MESSAGE);
                } else {

                     // lLamar al metodo guardar cuenta usuario
                        if (MetodosRegistroCuenta.guardarCuentaUsuario(nombre, apellidos, email, matricula, contrasena, esCoche)) {
                            JOptionPane.showMessageDialog(null, "Se acaba de registrar el usuario nombre " + nombre, "Correcto", JOptionPane.INFORMATION_MESSAGE);
                            InicioCuenta inicio = new InicioCuenta();
                            mostrarPanel(inicio);
                        } else {
                            JOptionPane.showMessageDialog(null, "Ha ocurrido un error al guardar el registro", "Error", JOptionPane.ERROR_MESSAGE);
                        }
   
                }      
            }
        }
    }
}
    

    }//GEN-LAST:event_jbregistroActionPerformed
    /** Evento me lleva a la ventana de inicio de sesion*/
    private void jltitulo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jltitulo3MouseClicked
         // Crea una instancia de InicioCuenta
        InicioSesion inicio = new InicioSesion();
        // Muestra la ventana InicioCuenta
        inicio.setVisible(true);
    }//GEN-LAST:event_jltitulo3MouseClicked
    /** Evento si al introducir los datos son erroneos, al cancelar vuelven a incilizarse los campos*/
    private void jbcancelarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarRegistroActionPerformed
       
        jtnombre.setText("Nombre");
        jtnombre.setForeground(Color.gray);
        jtapellidos.setText("Apellidos");
        jtapellidos.setForeground(Color.gray);
        jtemail.setText("Email");
        jtemail.setForeground(Color.gray);
        jtmatricula.setText("Matricula");
        jtmatricula.setForeground(Color.gray);
        jtcontrasena.setText("********");
        jtcontrasena.setForeground(Color.gray);
        jtrepetirContrasena.setText("********");
        jtrepetirContrasena.setForeground(Color.gray);
        
    }//GEN-LAST:event_jbcancelarRegistroActionPerformed
    /** Evento compotamiento de los campos al seleccionar*/
    private void jtnombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtnombreMouseClicked
    
        mrc.comportamientoCampos(jtnombre, "Nombre");
       
    }//GEN-LAST:event_jtnombreMouseClicked

    private void jtapellidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtapellidosMouseClicked
        mrc.comportamientoCampos(jtapellidos, "Apellidos");
    }//GEN-LAST:event_jtapellidosMouseClicked

    private void jtmatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtmatriculaMouseClicked
         mrc.comportamientoCampos(jtmatricula, "Matricula");
    }//GEN-LAST:event_jtmatriculaMouseClicked

    private void jtcontrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtcontrasenaMouseClicked
        mrc.comportamientoCampos(jtcontrasena, "********");
    }//GEN-LAST:event_jtcontrasenaMouseClicked

    private void jtrepetirContrasenaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtrepetirContrasenaMouseClicked
        mrc.comportamientoCampos(jtrepetirContrasena, "********");
    }//GEN-LAST:event_jtrepetirContrasenaMouseClicked

    private void jtemailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtemailMouseClicked
        mrc.comportamientoCampos(jtemail, "Email");
    }//GEN-LAST:event_jtemailMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxCoche;
    private javax.swing.JCheckBox jCheckBoxMoto;
    private javax.swing.JLabel jLiconCoche;
    private javax.swing.JLabel jLiconMoto;
    private javax.swing.JPanel jPanelApellidos;
    private javax.swing.JPanel jPanelContrasena;
    private javax.swing.JPanel jPanelContrasena1;
    private javax.swing.JPanel jPanelEmail;
    private javax.swing.JPanel jPanelMatricula;
    private javax.swing.JPanel jPanelNombre;
    private javax.swing.JButton jbcancelarRegistro;
    private javax.swing.JButton jbregistro;
    private javax.swing.JLabel jlapellidos;
    private javax.swing.JLabel jlcontrasena;
    private javax.swing.JLabel jlemail;
    private javax.swing.JLabel jlmatricula;
    private javax.swing.JLabel jlnombre;
    private javax.swing.JLabel jlrepetirContrasena;
    private javax.swing.JLabel jltitulo1;
    private javax.swing.JLabel jltitulo2;
    private javax.swing.JLabel jltitulo3;
    private javax.swing.JLabel jltitulo4;
    private javax.swing.JTextField jtapellidos;
    private javax.swing.JPasswordField jtcontrasena;
    private javax.swing.JTextField jtemail;
    private javax.swing.JTextField jtmatricula;
    private javax.swing.JTextField jtnombre;
    private javax.swing.JPasswordField jtrepetirContrasena;
    private vista.PanelRound panelRegistroCuenta;
    // End of variables declaration//GEN-END:variables

    private void mostrarPanel(InicioCuenta panel) {
       panel.setSize(428, 800);
       panel.setLocation(0,0);  
       
       panelRegistroCuenta.removeAll();
       panelRegistroCuenta.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
       panelRegistroCuenta.revalidate();
       panelRegistroCuenta.repaint();
    
}

}
