/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import controlador.MetodosInicio;
import controlador.MetodosReservar;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Javier Sanchez Gonzalez
 */
public class Reserva extends javax.swing.JPanel {

    MetodosInicio mi = new MetodosInicio();
    MetodosReservar mr = new MetodosReservar();

    private final double precioPorHora = 0.25;
    private LocalDate fecha;
    private int horas;
    private double precio;
    private String plaza;
    private final String nombre;
    private final String contrasena;
    private String coche;
    private String matricula;
    private String fechaTexto;
    private DateTimeFormatter formatter;
    private String fechaFormateada;
    private final float precioHora = 0.75f;
    private double total = 0.0f;

    /**
     * Creates new form RegistroCuenta
     */
    public Reserva() {
        initComponents();

        // Asignar valores predeterminados a los atributos nombre y contrasena
        this.nombre = "";
        this.contrasena = "";

        /*
        coche = jtcoche.getText().trim();
        matricula = jtmatricula.getText().trim();
        plaza = jtplaza.getText().trim();
        fechaTexto = jbcalendario.getText().trim();
         */
        // Poner jTexfield y jBotton el radio
        jbConfirmar.putClientProperty("FlatLaf.style", "arc: 15");
        jbcalendario.putClientProperty("FlatLaf.style", "arc: 15");
        jbcancelar.putClientProperty("FlatLaf.style", "arc: 15");
        jPdatosReserva.putClientProperty("FlatLaf.style", "arc: 15");

        // añadir a los jTextField iconos
        jtcoche.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("img/apellidos.svg"));
        jtmatricula.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("img/apellidos.svg"));
        jtplaza.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("img/apellidos.svg"));

        jtplaza.setText(plaza);
        jtplaza.setForeground(Color.black);
        System.out.print(plaza);
        /*
        // Obtener información del vehículo asociado al usuario
        // mi.devolverIdusuario(nombre, contrasena);
        Vehiculos vehiculo = mr.devuelveDatosVehiculo(nombre, contrasena);
        if (vehiculo != null) {
            jtmatricula.setText(vehiculo.getMatricula());
            jtcoche.setText(vehiculo.getEsCoche().toString());
        } else {
            // Si no se encontró ningún vehículo para el usuario, puedes mostrar un mensaje o dejar los campos vacíos
            jtmatricula.setText("");
            jtcoche.setText("");
        }
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTiket = new javax.swing.JPanel();
        jltitulo2 = new javax.swing.JLabel();
        jlnombre1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jPdatosReserva = new javax.swing.JPanel();
        jtcoche = new javax.swing.JTextField();
        jtplaza = new javax.swing.JTextField();
        jtmatricula = new javax.swing.JTextField();
        jlnombre2 = new javax.swing.JLabel();
        jlnombre3 = new javax.swing.JLabel();
        jltiempo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jlnombre5 = new javax.swing.JLabel();
        jttotal = new javax.swing.JTextField();
        jbcalendario = new javax.swing.JButton();
        jTexthora = new javax.swing.JTextField();
        jlnombre6 = new javax.swing.JLabel();
        jbConfirmar = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();
        jltitulo4 = new javax.swing.JLabel();

        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(428, 800));

        jPanelTiket.setBackground(new java.awt.Color(249, 251, 255));
        jPanelTiket.setMaximumSize(null);
        jPanelTiket.setPreferredSize(new java.awt.Dimension(430, 800));

        jltitulo2.setBackground(new java.awt.Color(249, 251, 255));
        jltitulo2.setFont(new java.awt.Font("Stencil", 0, 20)); // NOI18N
        jltitulo2.setForeground(new java.awt.Color(39, 59, 244));
        jltitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltitulo2.setText("DETALLE PLAZA RESERVADA");
        jltitulo2.setPreferredSize(new java.awt.Dimension(273, 30));

        jlnombre1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlnombre1.setForeground(new java.awt.Color(0, 0, 0));
        jlnombre1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlnombre1.setText("Tiempo duración");
        jlnombre1.setToolTipText("");
        jlnombre1.setPreferredSize(new java.awt.Dimension(51, 17));

        jSlider1.setBackground(new java.awt.Color(39, 59, 244));
        jSlider1.setForeground(new java.awt.Color(0, 0, 0));
        jSlider1.setMaximum(24);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setToolTipText("Selecciona la horas que quieres reservar la plaza");
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jPdatosReserva.setBackground(new java.awt.Color(198, 212, 255));
        jPdatosReserva.setForeground(new java.awt.Color(198, 212, 255));
        jPdatosReserva.setPreferredSize(new java.awt.Dimension(335, 82));

        jtcoche.setBackground(new java.awt.Color(198, 212, 255));
        jtcoche.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jtcoche.setForeground(new java.awt.Color(153, 153, 153));
        jtcoche.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtcoche.setText("vehiculo");
        jtcoche.setToolTipText("Introduce tu nombre minimo tiene que tener 3 caracteres");
        jtcoche.setPreferredSize(new java.awt.Dimension(335, 50));

        jtplaza.setBackground(new java.awt.Color(198, 212, 255));
        jtplaza.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jtplaza.setForeground(new java.awt.Color(153, 153, 153));
        jtplaza.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtplaza.setText("P01");
        jtplaza.setToolTipText("Introduce tu nombre minimo tiene que tener 3 caracteres");
        jtplaza.setPreferredSize(new java.awt.Dimension(335, 50));

        jtmatricula.setBackground(new java.awt.Color(198, 212, 255));
        jtmatricula.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jtmatricula.setForeground(new java.awt.Color(153, 153, 153));
        jtmatricula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtmatricula.setText("matricula");
        jtmatricula.setToolTipText("Introduce tu nombre minimo tiene que tener 3 caracteres");
        jtmatricula.setPreferredSize(new java.awt.Dimension(335, 50));

        jlnombre2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlnombre2.setForeground(new java.awt.Color(0, 0, 0));
        jlnombre2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlnombre2.setText("Matricula");
        jlnombre2.setToolTipText("");
        jlnombre2.setPreferredSize(new java.awt.Dimension(51, 17));

        jlnombre3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlnombre3.setForeground(new java.awt.Color(0, 0, 0));
        jlnombre3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlnombre3.setText("Tipo de vehiculo");
        jlnombre3.setToolTipText("");
        jlnombre3.setPreferredSize(new java.awt.Dimension(51, 17));

        jltiempo.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jltiempo.setForeground(new java.awt.Color(0, 0, 0));
        jltiempo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jltiempo.setText("Tiempo");
        jltiempo.setToolTipText("");
        jltiempo.setPreferredSize(new java.awt.Dimension(51, 17));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(39, 59, 244));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 9, 50));

        jlnombre5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlnombre5.setForeground(new java.awt.Color(0, 0, 0));
        jlnombre5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlnombre5.setText("TOTAL");
        jlnombre5.setToolTipText("");
        jlnombre5.setPreferredSize(new java.awt.Dimension(51, 17));
        jPanel1.add(jlnombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 40));

        jttotal.setBackground(new java.awt.Color(153, 204, 255));
        jttotal.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jttotal.setForeground(new java.awt.Color(0, 0, 0));
        jttotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jttotal.setText("00");
        jttotal.setToolTipText("Introduce tu nombre minimo tiene que tener 3 caracteres");
        jttotal.setPreferredSize(new java.awt.Dimension(335, 50));
        jPanel1.add(jttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 130, 40));

        jbcalendario.setBackground(new java.awt.Color(39, 59, 244));
        jbcalendario.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jbcalendario.setForeground(new java.awt.Color(255, 255, 255));
        jbcalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/calendario.png"))); // NOI18N
        jbcalendario.setToolTipText("Boton muesetra el calendario para selecicionar fecha");
        jbcalendario.setPreferredSize(new java.awt.Dimension(124, 49));
        jbcalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcalendarioActionPerformed(evt);
            }
        });

        jTexthora.setBackground(new java.awt.Color(198, 212, 255));
        jTexthora.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jTexthora.setForeground(new java.awt.Color(153, 153, 153));
        jTexthora.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jlnombre6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jlnombre6.setForeground(new java.awt.Color(0, 0, 0));
        jlnombre6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlnombre6.setText("Plaza de aparcamiento");
        jlnombre6.setToolTipText("");
        jlnombre6.setPreferredSize(new java.awt.Dimension(51, 17));

        javax.swing.GroupLayout jPdatosReservaLayout = new javax.swing.GroupLayout(jPdatosReserva);
        jPdatosReserva.setLayout(jPdatosReservaLayout);
        jPdatosReservaLayout.setHorizontalGroup(
            jPdatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
            .addGroup(jPdatosReservaLayout.createSequentialGroup()
                .addGroup(jPdatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPdatosReservaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPdatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtcoche, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlnombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtplaza, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPdatosReservaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jlnombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPdatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPdatosReservaLayout.createSequentialGroup()
                        .addGroup(jPdatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlnombre2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtmatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPdatosReservaLayout.createSequentialGroup()
                        .addGroup(jPdatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jltiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTexthora, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPdatosReservaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbcalendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPdatosReservaLayout.setVerticalGroup(
            jPdatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPdatosReservaLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPdatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlnombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlnombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPdatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtcoche, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPdatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jltiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlnombre6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPdatosReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtplaza, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexthora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbcalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jbConfirmar.setBackground(new java.awt.Color(43, 220, 61));
        jbConfirmar.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jbConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        jbConfirmar.setText("Confirmar");
        jbConfirmar.setToolTipText("Boton cofirmar el pago");
        jbConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbConfirmar.setPreferredSize(new java.awt.Dimension(124, 49));
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        jbcancelar.setBackground(new java.awt.Color(255, 3, 3));
        jbcancelar.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        jbcancelar.setForeground(new java.awt.Color(255, 255, 255));
        jbcancelar.setText("Cancelar");
        jbcancelar.setToolTipText("Boton cancela el pago y vuelve a la panta del parking");
        jbcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbcancelar.setPreferredSize(new java.awt.Dimension(124, 49));
        jbcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcancelarActionPerformed(evt);
            }
        });

        jltitulo4.setFont(new java.awt.Font("Lucida Sans", 0, 20)); // NOI18N
        jltitulo4.setForeground(new java.awt.Color(51, 51, 51));
        jltitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltitulo4.setText("Tiket reserva plaza");
        jltitulo4.setPreferredSize(new java.awt.Dimension(273, 30));

        javax.swing.GroupLayout jPanelTiketLayout = new javax.swing.GroupLayout(jPanelTiket);
        jPanelTiket.setLayout(jPanelTiketLayout);
        jPanelTiketLayout.setHorizontalGroup(
            jPanelTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jltitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTiketLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jltitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(jPanelTiketLayout.createSequentialGroup()
                .addGroup(jPanelTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTiketLayout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jPdatosReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTiketLayout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jlnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanelTiketLayout.setVerticalGroup(
            jPanelTiketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTiketLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jltitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jltitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPdatosReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Evento al pulsar el boton del calendario muestra la fecha actual
     *
     * @param evt
     */
    private void jbcalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcalendarioActionPerformed

        // Obtener la fecha actual
        fecha = LocalDate.now();
        formatter = DateTimeFormatter.ofPattern("yyyy/MM/dd"); //  formato deseado
        fechaFormateada = fecha.format(formatter); // Formato fecha
        jbcalendario.setText(fechaFormateada);

    }//GEN-LAST:event_jbcalendarioActionPerformed
    /**
     * Evento se le pasa el metodo MostrarPanel eliminando el actual y mostrando
     * el que se le pasa calculo de el tiempo de estacionamiento
     *
     * @param evt
     */
    private void jbcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcancelarActionPerformed
        Parking parking = new Parking();
        mostrarPanel(parking);
    }//GEN-LAST:event_jbcancelarActionPerformed
    /**
     * Evento comprobacion que los campos no este vacios para cofirmar y pagar
     *
     * @param evt
     */
    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed

        JOptionPane.showMessageDialog(this, "La reserva del aparcamiento se ha completado.", "Reserva completada", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jbConfirmarActionPerformed
    /**
     * Evento muestra en el campo texto horas segun la selecion del slider
     *
     * @param evt
     */
    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        horas = jSlider1.getValue();
        jTexthora.setText(String.valueOf(horas));
        jTexthora.setForeground(Color.black);
        total = (precioPorHora * horas);
        jttotal.setText(String.valueOf(total));

        jtcoche.setText("Coche");
        jtmatricula.setText("1234ABD");
        jtplaza.setText("P01");
        jtcoche.setForeground(Color.black);
        jtmatricula.setForeground(Color.black);
        jtplaza.setForeground(Color.black);

    }//GEN-LAST:event_jSlider1StateChanged
    /**
     * Metodo elimna el panel actual y muestra el que se le pasa
     *
     * @param panel
     */
    private void mostrarPanel(JPanel panel) {
        panel.setSize(428, 800);
        panel.setLocation(0, 0);
        jPanelTiket.removeAll();
        jPanelTiket.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanelTiket.revalidate();
        jPanelTiket.repaint();
    }

    public void setPlazaSeleccionada(String plazaSeleccionada) {
        this.plaza = plazaSeleccionada;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTiket;
    private javax.swing.JPanel jPdatosReserva;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTexthora;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbcalendario;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JLabel jlnombre1;
    private javax.swing.JLabel jlnombre2;
    private javax.swing.JLabel jlnombre3;
    private javax.swing.JLabel jlnombre5;
    private javax.swing.JLabel jlnombre6;
    private javax.swing.JLabel jltiempo;
    private javax.swing.JLabel jltitulo2;
    private javax.swing.JLabel jltitulo4;
    private javax.swing.JTextField jtcoche;
    private javax.swing.JTextField jtmatricula;
    private javax.swing.JTextField jtplaza;
    private javax.swing.JTextField jttotal;
    // End of variables declaration//GEN-END:variables

}
